### Retrieve all trips
GET {{url}}/api/trips

### Retrieve trip by id
GET {{url}}/api/trips/1

### Add a new trip
POST {{url}}/api/trips
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "startTime": "10:00:00",
  "endTime": "18:00:00",
  "longitude": "45.0",
  "latitude": "90.0",
  "name": "New Adventure",
  "price": 500.0,
  "category": "snow",
  "guide": {
    "id": 1
  }
}


### Update trip by id
PUT {{url}}/api/trips/8
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "id": 1,
  "startTime": "10:00:00",
  "endTime": "18:00:00",
  "longitude": "45.0",
  "latitude": "90.0",
  "name": "Updated New Adventure",
  "price": 500.0,
  "category": "snow",
  "guide": {
    "id": 1
  }
}

### Delete trip by id
DELETE {{url}}/api/trips/5
Authorization: Bearer {{jwt_token}}

### Set guide for a specific trip
PUT {{url}}/api/trips/8/guides/2
Authorization: Bearer {{jwt_token}}

### Retrieve all trips for a specific guide
GET {{url}}/api/trips/guides/1
Authorization: Bearer {{jwt_token}}

### Populate trips
POST {{url}}/api/trips/populate
Authorization: Bearer {{jwt_token}}

### Retrieve all trips for a specific category
GET {{url}}/api/trips/category/beach
Authorization: Bearer {{jwt_token}}

### See total price of all trips for all guides
GET {{url}}/api/trips/guide/totalPrice
Authorization: Bearer {{jwt_token}}

### Retrieve all packing items for a specific trip
GET {{url}}/api/trips/category/beach/packingItems
Authorization: Bearer {{jwt_token}}

### Retrieve total weight of all packing items for a specific trip
GET {{url}}/api/trips/1/totalWeight
Authorization: Bearer {{jwt_token}}